version: "3"
services:
  mirai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miraibot
    hostname: miraibot
    restart: unless-stopped
    tty: true
    stdin_open: true
    #ports:
      #- "6700:6700"
    volumes:
      - ./mirai:/mirai
